### PR TITLE
Network/interfaces(Chentao 27504)

### PR DESCRIPTION
**Pull request by Allwithyou999**
https://redmine.ixsystems.com/issues/27504

Done

### CODE REVIEW

**Comment by erinix** [comment]
Is daisuke working on this with you, chentao?

**Comment by erinix** [comment]
could you add some simple regex validation for ipv4 and ipv6 to further make these fields less confusing?

**Comment by Allwithyou999** [comment]
@erinix Yeah, I can add

**Comment by Allwithyou999** [comment]
@erinix I added regex validation for ipv4 and ipv6

**Comment by erinix** [comment]
LGTM

**Pull request merged**
