### PR TITLE
Fix 65139

### PR DESCRIPTION
**Pull request by vaibhav-rbs**

### CODE REVIEW

**Comment by vaibhav-rbs** [comment]
please merge #1728 to master as this has some changes which are based directly on PR aforementioned.

please ask me question if you have doubts

**Comment by erinix** [comment]
rebuild

**Comment by erinix** [comment]
rebuild

**Comment by erinix** [comment]
rebuild

**Comment by erinix** [comment]
rebuild

**Comment by erinix** [comment]
rebuild

**Pull request merged**
