### PR TITLE
New GUI log out operation shouldn't have confirmation checkbox in it(Chentao fix 27446)

### PR DESCRIPTION
**Pull request by Allwithyou999**
https://redmine.ixsystems.com/issues/27446

Done

### CODE REVIEW

**Comment by erinix** [comment]
the button for logging out appears to still be greyed out even though the checkbox is hidden, you should add some logic to the [disabled] field for the button to not be greyed out when hideCheckBox = true;

**Comment by Allwithyou999** [comment]
@erinix right, That is not the latest version and a commit was missed.Sorry

**Comment by Allwithyou999** [comment]
Resolved.

**Comment by erinix** [comment]
LGTM

**Pull request merged**
