### PR TITLE
NAS-107472

### PR DESCRIPTION
**Pull request by dszidi**
Add TrueNAS minis  to enclosure management supported products list

### CODE REVIEW

**Review by erinix — APPROVED** [review]

**Comment by erinix** [comment]
backport

**Comment by erinix** [comment]
backport

**Comment by erinix** [comment]
backport

**Review by darkfiberiru — COMMENTED** [review]
Lgtm

**Review by darkfiberiru — COMMENTED** [review]
Change looks good to me

**Pull request merged**
