### PR TITLE
lola please review and merge my changes to master.

### PR DESCRIPTION
**Pull request by vaibhav-rbs**

### CODE REVIEW

**Comment by kmoore134** [comment]
Compile failed

https://builds.ixsystems.com/jenkins/job/FreeNAS%20-%20Pull%20Request%20Builder%20(webui)/18/artifact/artifacts/ports/latest-per-pkg/freenas-webui/11_1409/

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by vaibhav-rbs** [comment]
Jenkins: retest this please

**Comment by vaibhav-rbs** [comment]
Jenkins: retest this please

**Comment by vaibhav-rbs** [comment]
Jenkins: retest this please

**Comment by dszidi** [comment]
Read the code and no obvious problems. Merged fine locally and Angular compiled it aot ok too. LGTM.

**Pull request merged**
