### PR TITLE
Update de.po

### PR DESCRIPTION
**Pull request by ByteHD**
added a bunch of german translations

### CODE REVIEW

**Comment by erinix** [comment]
looks like you have some merge conflicts

**Comment by ByteHD** [comment]
oops, didn't notice them. Should I create an new request with a fix and close this one or can you remove the conflicts?

**Comment by erinix** [comment]
Yea go ahead and make a new request if that is easier, there are quite a few conflicts so I don't know if removing them by hand is feasible

**Comment by ByteHD** [comment]
Should look better now

**Pull request merged**
