### PR TITLE
Storage View Disks UI(Chentao fix #26960)

### PR DESCRIPTION
**Pull request by Allwithyou999**
https://redmine.ixsystems.com/issues/26960

Done

### CODE REVIEW

**Comment by lola27** [comment]
@Allwithyou999 All looks good to me except one thing, when a disk is successfully wiped, it doesn't go back to the disk list page. And maybe a double confirmation for wiping disk is needed, just the same as delete confirm dialogue. thanks.

**Comment by Allwithyou999** [comment]
@lola27 Thanks for your reviewing. I will check and resolve soon.

**Comment by Allwithyou999** [comment]
@lola27 Added a double confirmation for wiping disk.

**Comment by erinix** [comment]
One request, could you add a link on the menu bar that goes to the view disks page?

**Comment by Allwithyou999** [comment]
@erinix Yes, I will add soon.

**Comment by erinix** [comment]
Could you please finish that final request and fix the merge conflict so I can merge it.  Everything looks good other than that.

**Comment by Allwithyou999** [comment]
Yes, Please allow me 5 minutes

**Comment by erinix** [comment]
No worries, I just didn't want this PR to get stale :)

**Comment by Allwithyou999** [comment]
@erinix I added "Disks" menu in the left sidebar.

**Comment by erinix** [comment]
Jenkins: retest this please

**Comment by erinix** [comment]
LGTM

**Pull request merged**
