### PR TITLE
Fix tour show logic in Account/Users, remove "you just closed User To…

### PR DESCRIPTION
**Pull request by wblock**
…ur" annoybot

### CODE REVIEW

**Comment by erinix** [comment]
please merge master to bring in the build fix

**Comment by erinix** [comment]
rebuild

**Comment by erinix** [comment]
the showTour !== "false" seems to make the tour show up every time I click into that page.

**Comment by wblock** [comment]
> the showTour !== "false" seems to make the tour show up every time I click into that page.

That is what it did for me with "true" and new user profiles (my Selenium setup starts with a new profile each time).  This might be an interaction with the preferences thing.  Which should be a button anyway.  People aren't going to watch the tour every time they log in.  At most, they will want to see it once when it is new to them.  I'll try to figure out what this test really means.

**Comment by erinix** [comment]
rebuild

**Pull request merged**
