### PR TITLE
Fix 27823

### PR DESCRIPTION
**Pull request by vaibhav-rbs**

### CODE REVIEW

**Comment by vaibhav-rbs** [comment]
Jenkins: retest this please

**Comment by vaibhav-rbs** [comment]
Jenkins: retest this please

**Comment by vaibhav-rbs** [comment]
Jenkins: retest this please

**Comment by lola27** [comment]
@vaibhav-rbs The default value for 'home directory' should be empty or others instead of '/nonexistent', otherwise there will be an error when editing that user.

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by lola27** [comment]
LGTM

**Pull request merged**
