### PR TITLE
Fix/vert align table headers 34585

### PR DESCRIPTION
**Pull request by dkmullen**
- aligns text vertically in entity table headers
- aligns pager in entity table footers
- sets all headers to same height as rows and footers for consistent appearance
- makes footer flexible in height to allow for pager expansion

### CODE REVIEW

**Comment by erinix** [comment]
This looks good to me, what do you think @dszidi ?

**Comment by erinix** [comment]
rebuild

**Comment by dszidi** [comment]
Don't have a way to check it out on a working FreeNAS system ATM, but I don't see anything that would indicate any problems. LGTM

**Comment by dkmullen** [comment]
rebuild

**Pull request merged**
