### PR TITLE
Scrub task CRUD (Chentao fix #26908)

### PR DESCRIPTION
**Pull request by Allwithyou999**
https://redmine.ixsystems.com/issues/26908
Done.

### CODE REVIEW

**Comment by lola27** [comment]
@Allwithyou999 All looks good to me, except when editing a scrub task, the volume name is not shown, need to select it again.

**Comment by Allwithyou999** [comment]
@lola27 Yes, I'll fix soon.

**Comment by Allwithyou999** [comment]
@lola27 I fixed the issue.

**Comment by lola27** [comment]
LGTM

**Pull request merged**
