### PR TITLE
feat(vm): Use recommended value as default for volblocksize

### PR DESCRIPTION
**Pull request by skarekrow**
512 bytes is too small for an optimal volblocksize, this removes that, and creating a zvol is moved to the VM middleware plugin where it should live.

Related PR: https://github.com/freenas/freenas/pull/1451

Ticket: #35737

### CODE REVIEW

**Comment by skarekrow** [comment]
This is now done, https://github.com/freenas/freenas/pull/1451 must be merged before this.

**Comment by erinix** [comment]
could you please fix your merge conflicts

**Comment by vaibhav-rbs** [comment]
freenas# zfs get volblocksize vb-disk/d0/meh-qouylr
NAME                   PROPERTY      VALUE     SOURCE
vb-disk/d0/meh-qouylr  volblocksize  16K       -

**Comment by erinix** [comment]
rebuild

**Pull request merged**
