### PR TITLE
Update pl.po

### PR DESCRIPTION
**Pull request by adam23450**
Translations continued

### CODE REVIEW

**Comment by erinix** [comment]
you should add an entry into the README.md that lists polish as one of the languages :)

**Comment by adam23450** [comment]
ok

**Comment by adam23450** [comment]
Already :)

**Comment by adam23450** [comment]
When will the language be available on the NAS?

**Comment by erinix** [comment]
master goes into nightlies, you will see these updates in the next nightly and then in 12.0 when we release it, if you want your changes to go into an 11.3 version you should also make translations to the branch freenas/11.3-stable

**Comment by adam23450** [comment]
How do I update it so that I can see the translations?

**Comment by erinix** [comment]
these current changes will go into tonight's nightly, so you could download that and run it in VM (I wouldn't suggest using it on a production box just yet)

**Comment by adam23450** [comment]
I understand. Thank you. Meanwhile, I'm going on with the further translation :)

**Comment by erinix** [comment]
you're welcome, also I had a change request on your README PR, we are trying to keep the languages in that list in alphabetic order :)

**Comment by adam23450** [comment]
ok

**Pull request merged**
