### PR TITLE
Ticket: 26481

### PR DESCRIPTION
**Pull request by Nesma1988**
Fixes: https://redmine.ixsystems.com/issues/26481
Desc: Saving System-Advanced settings shouldn't validate serial choice if not enabled

### CODE REVIEW

**Comment by Nesma1988** [comment]
@dasukeImaimobile I have checked the issue however I couldn't reproduce the same, although I have made some improvements(just in case). Please check the video because during the development this was not found. Also, I have recorded a video about this bug is not been reproduced in my machine. 

https://www.dropbox.com/s/ewj8a1v36dp6vcp/out-3.ogv?dl=0

**Comment by dasukeImaimobile** [comment]
@Nesma1988 I will double check soon and let you know.

**Comment by Nesma1988** [comment]
@dasukeImaimobile  thank you!

**Comment by Nesma1988** [comment]
@dasukeImaimobile branch updated.!

**Comment by Nesma1988** [comment]
@dasukeImaimobile I have double checked it; works fine.

**Comment by mactanxin** [comment]
LGTM

**Comment by dasukeImaimobile** [comment]
@Nesma1988 It worked for me, as well, thanks

**Pull request merged**
