### PR TITLE
implemented legecy UI updater train switch logic.

### PR DESCRIPTION
**Pull request by vaibhav-rbs**
adding @william-gr as well as he maybe able to point out some of wrong workflow as Legacy UI train switch logic was implemented here as  well.

### CODE REVIEW

**Comment by erinix** [comment]
rebuild

**Comment by erinix** [comment]
rebuild

**Comment by erinix** [comment]
Please add T() markers where appropriate so that it can be translated

**Comment by vaibhav-rbs** [comment]
rebuild

**Comment by erinix** [comment]
rebuild

**Comment by erinix** [comment]
rebuild

**Comment by erinix** [comment]
rebuild

**Pull request merged**
