### PR TITLE
Daisuke webui fix 24727

### PR DESCRIPTION
**Pull request by dasukeImaimobile**
Completed https://bugs.freenas.org/issues/24727

### CODE REVIEW

**Comment by lola27** [comment]
@dasukeImaimobile I cannot see the download key dialog when creating an encrypted pool. Could you give us a screenshot if you have any? thanks

**Comment by dasukeImaimobile** [comment]
Yeah, I will make a video soon.

**Comment by dasukeImaimobile** [comment]
https://www.dropbox.com/s/q0qjnpaz6aobtv5/screen_pool_download_key.mov?dl=0
@lola27 Please review and let me know if you have any question.
I am available all day long. Thanks. :)

**Comment by vaibhav-rbs** [comment]
LGTM, I can see the WARNING BOX as well.

**Comment by dasukeImaimobile** [comment]
Thanks @vaibhav-rbs

**Pull request merged**
