### PR TITLE
Fix 27055

### PR DESCRIPTION
**Pull request by vaibhav-rbs**

### CODE REVIEW

**Comment by lola27** [comment]
@vaibhav-rbs Your PR works well, but the field 'Create a new Primary Group for the user' will show up first and then disappear. I suggest moving ``` _.find(this.fieldConfig, {name : "bsdusr_creategroup"}).isHidden = true;``` into the top of function afterInit(). Thanks.

**Comment by erinix** [comment]
Jenkins: retest this please

**Comment by erinix** [comment]
Jenkins: retest this please

**Comment by vaibhav-rbs** [comment]
@lola27 I have made edit to my pr as requested please check. ty

**Comment by lola27** [comment]
LGTM

**Pull request merged**
