### PR TITLE
Re-add jail form, tooltip, and wizard improvements

### PR DESCRIPTION
**Pull request by Mrt134**
From previous reverted commits - cherry picked all the non-controversial work to improve the Jails forms.

### CODE REVIEW

**Comment by lola27** [comment]
Hi Tim, everything looks good to me except the Back button and Next button. Could you keep the ```color="accent"``` for the Back button and ```color="primary"``` for the Next button on entity-wizard? and don't need to add ```type="button"``` to them. Otherwise the two buttons will be in gray and press Enter will not go to next step. Thanks.

**Comment by Mrt134** [comment]
Sure, I'll adjust that now.

**Comment by lola27** [comment]
👍 Thanks. Back button needs  ```color="accent"``` too :)

**Comment by lola27** [comment]
LGTM

**Pull request merged**
