### PR TITLE
Fix incorrect translations (es.po)

### PR DESCRIPTION
**Pull request by FelixSabando**

### CODE REVIEW

**Comment by erinix** [comment]
please also make a patch against freenas/11.2-stable and submit more patches :)  your Spanish is probably better than mine :D, I just put these in to test the translations

**Comment by FelixSabando** [comment]
Helo erinix. 
I am from spain, jeje.
I checked the "freenas/os" repositry and I only found the .po file located on "os/contrib/dialog/po/es.po ", It is correct.
If there is any other file to check please tel me (I am new on freenas and GitHub and I may not found the file that you want).
I will continue translating this file ("es.po" on "webui" repository).
If you need any other thing, please tell me.
Kind regards.

**Comment by erinix** [comment]
Hello Felix, I am happy to work with you on translating these things.  I am not very familiar with the freenas/os repository either, what I was referring to was the branch "freenas/11.2-stable" within the webui repo.  The "freenas/11.2-stable" branch is where 11.2 releases are pulled from so if you want to see your translations go into those versions you will want to also translate there, master will go into 11.3 and other future releases.

**Comment by FelixSabando** [comment]
Thanks!! It is my first time on GitHub...
I changed the "freenas/11.2-stable" (for the future I will change both).
Kind regards.

**Pull request merged**
