### PR TITLE
NAS-107821 / 11.3 / NAS-107821 fixed replication edit issue

### PR DESCRIPTION
**Pull request by lola27**

### CODE REVIEW

**Review by erinix — APPROVED** [review]

**Comment by kenshirothefist** [comment]
@erinix is it possible to manually apply this fix (i.e. temporary editing a particular file on the freenas installation) until a new version / fix is released?

**Comment by amelchio** [comment]
This PR can be patched upon FreeNAS 11.3-U5 with the following shell command:
```
perl -p -i.orig -e 's/(&&"dedup"!==a)/$1&&"large_block"!==a/' /usr/local/www/webui/11.6fb233ce87e72d4b5eca.js
```

To revert:
```
mv /usr/local/www/webui/11.6fb233ce87e72d4b5eca.js.orig /usr/local/www/webui/11.6fb233ce87e72d4b5eca.js
```

**Comment by jmpalacios** [comment]
> This PR can be patched upon FreeNAS 11.3-U5 with the following shell command:
> 
> ```
> perl -p -i.orig -e 's/(&&"dedup"!==a)/$1&&"large_block"!==a/' /usr/local/www/webui/11.6fb233ce87e72d4b5eca.js
> ```
> 
> To revert:
> 
> ```
> mv /usr/local/www/webui/11.6fb233ce87e72d4b5eca.js.orig /usr/local/www/webui/11.6fb233ce87e72d4b5eca.js
> ```

This worked perfectly for me, I re-updated to 11.3-U5, applied the patch, and regained control of my replication tasks.

Thanks!

**Comment by thefoster** [comment]
This patch alone didn't work for me, even after reverting to u4.1.
I had to re-revert to u5 to re-enable editing of replication tasks.

**Comment by amelchio** [comment]
My patch command will only work with FreeNAS 11.3-U5.

I don't remember clearing the browser cache but it might be needed to get the fixed version to download.

**Comment by Halfang** [comment]
This worked for me in 11.3-U5.  

Make sure you force-refresh Freenas UI via ctrl+F5

**Comment by mschmidty4** [comment]
Thanks for this awesome fix...worked for me in 11.3-U5.

**Pull request merged**
