### PR TITLE
converted to use @angular/cli  and cleaned up a few broken imports

### PR DESCRIPTION
**Pull request by Steven-Harris**
I wanted to go ahead and get a PR started to show you my progress. I seem to have broken the websocket connection. But I will update this PR when I figure out what I am missing, unless one of you can spot it first.

### CODE REVIEW

**Comment by erinix** [comment]
Nice, I'll take a look at what you have so far.  Let me know when it is complete and I'll do more testing with it.

**Comment by Steven-Harris** [comment]
I have the websocket connected but I think there is still something slightly off. 
TODO:
- [ ] find what happened to the logout button
- [ ] fix breadcrumbs
- [ ] fix meau when collapsing 
- [ ] troubleshoot "unexpected json" errors

**Comment by Steven-Harris** [comment]
Ready for merge into master

**Comment by kmoore134** [comment]
Test - Please Ignore

**Pull request merged**
