### PR TITLE
Additional Dataset/ZVOL "Advanced Mode" Properties and Replace to new API(Chentao fix 24734)

### PR DESCRIPTION
**Pull request by Allwithyou999**
https://redmine.ixsystems.com/issues/24734

Done

### CODE REVIEW

**Comment by amotin** [comment]
Just a thought: working on the large project in private branch you could do rebases instead of merges, and/or clean up the commit history a bit before submitting it for public review.

**Comment by erinix** [comment]
If I try to save a dataset without a quota it tells me "[EFAULT] Failed to create dataset: 'quota' must be a number" it should allow making quota-less datasets

**Comment by Allwithyou999** [comment]
@erinix yeah, I will check soon

**Comment by Allwithyou999** [comment]
@erinix I double checked but I can't meet your issue.
Did you get this issue in "Add Dataset" or "Edit dataset" page?

**Comment by Allwithyou999** [comment]
@erinix And did you upgrade FreeNAS server to the latest version?
If not so, you need to upgrade to the latest version.

**Comment by Allwithyou999** [comment]
And I found another issue on API side. William said that he would fix it soon.

**Comment by erinix** [comment]
I may have been using an old version to test against.  Let me know when this other API issue is fixed and I will try again

**Comment by Allwithyou999** [comment]
@erinix Ok, I will let you know immediately once it is fixed.

**Comment by Allwithyou999** [comment]
@erinix API issues were fixed. You can take a test now.

**Comment by Allwithyou999** [comment]
@erinix you need to take a test on the latest version(FreeNAS-11-MASTER-201712291544).

**Comment by erinix** [comment]
LGTM

**Pull request merged**
