### PR TITLE
WebAuthn support

### PR DESCRIPTION
**Pull request by jeamland**
Adds UI elements and code to support WebAuthn. Relies on related changes in freenas/freenas.

### CODE REVIEW

**Comment by jeamland** [comment]
Related changes: https://github.com/freenas/freenas/pull/1153

**Comment by erinix** [comment]
Looks like you have an aot compiling error ```ERROR in src/app/pages/account/users/user-form/user-form.component.ts(412,19): error TS2339: Property 'credentials' does not exist on type 'Navigator'.
31msrc/app/views/sessions/signin/signin.component.ts(90,17): error TS2339: Property 'credentials' does not exist on type 'Navigator'.```

**Comment by jeamland** [comment]
Yeah, this is because the TypeScript bits don't know about navigator.credentials. I tried various ways to fix this but none seemed to work.

**Comment by erinix** [comment]
Perhaps try navigator['credentials'].create?

**Comment by erinix** [comment]
rebuild

**Comment by erinix** [comment]
rebuild

**Comment by erinix** [comment]
rebuild

**Comment by erinix** [comment]
rebuild

**Comment by erinix** [comment]
rebuild

**Pull request closed without merging**
