### PR TITLE
Daisuke webui

### PR DESCRIPTION
**Pull request by dasukeImaimobile**
I completed an issue, #26190.
The latest commit is 7deac3e1976e4e06bee570fccceda8fedded3fd8

Please review and let me know.

### CODE REVIEW

**Comment by kmoore134** [comment]
Jenkins: add to whitelist

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by dasukeImaimobile** [comment]
I fixed a hidden issue of volumes list ui and commit the fixed version. Please review together.

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by dasukeImaimobile** [comment]
I completed the double confirmation issue, https://bugs.freenas.org/issues/26201

**Comment by lola27** [comment]
LGTM

**Pull request merged**
