### PR TITLE
Fix 25825

### PR DESCRIPTION
**Pull request by Nesma1988**
Fixes: https://redmine.ixsystems.com/issues/25825
Showing re-silvering process in topbar

### CODE REVIEW

**Comment by lola27** [comment]
@Nesma1988 I saw the icon shows when getting the response from middleware and then disappeared few seconds until next response gotten. I suggest making the icon shows all the way start from the resilver start and end of the resilver finished. And when clicking the icon, show the process/percentage of the task. Thanks.

**Comment by Nesma1988** [comment]
@lola27 
> when clicking the icon, show the process/percentage of the task.

This is done. When you click the icon it will popup a snackbar in the bottom showing `Resilvering Pool A - X%`

> I saw the icon shows when getting the response from middleware and then disappeared few seconds until next response gotten. I suggest making the icon shows all the way start from the resilver start and end of the resilver finished.

I will look into it...

**Comment by Nesma1988** [comment]
@lola27 
Fix is done, please take a look.

**Comment by lola27** [comment]
LGTM

**Pull request merged**
