### PR TITLE
NAS-107751 / 20.12 / Nas 107751a

### PR DESCRIPTION
**Pull request by dkmullen**
Must be merged after https://github.com/freenas/webui/pull/4795
Moves config actions in General Settings dashboard into the new title area (created in the above PR)

### CODE REVIEW

**Review by Mrt134 — APPROVED** [review]
Looks good!

**Review by dszidi — COMMENTED** [review]
The actual code looks fine. I'm wondering if we can come up with a better button label than "Config Files". Maybe "Configure" might be more appropriate? Maybe Tim can chime in?

**Comment by Mrt134** [comment]
The button label "Config Files" does seem a little ambiguous for a label that has multiple actions underneath. What about changing to be a little more descriptive, something like "Manage Config", "Manage System Configuration", "Config File Actions", "Configuration Management"?

**Review by dszidi — APPROVED** [review]
I like the suggestions. This probably will require some consideration and I don't want to hold up this PR. I will make a new ticket and include these comments 

LGTM

**Pull request merged**
