### PR TITLE
Reword "system is not yet available" to "Attempting to connect"

### PR DESCRIPTION
**Pull request by wblock**
Make this message more clear about what is going on and what might cause connection problems.

### CODE REVIEW

**Comment by erinix** [comment]
This message will eventually show up on TrueNAS too so perhaps try wording it without "FreeNAS" in the name

**Comment by wblock** [comment]
I considered that, but being too generic won't help the user much.  Investigating whether there is some kind of NAS type variable that can be used here to avoid hardcoded assumptions.

**Comment by erinix** [comment]
There is but if the websocket service isn't available there is no way the UI will know which it is

**Comment by dlavigne** [comment]
Now that there is an associated ticket, please also remove the other 2 lines from the message as they are irrevelant.

**Comment by erinix** [comment]
please merge master to bring in the build fix

**Comment by erinix** [comment]
LGTM

**Pull request merged**
