### PR TITLE
Ticket 145583

### PR DESCRIPTION
**Pull request by Nesma1988**
Fixes: https://bugs.freenas.org/issues/26128#change-145583

### CODE REVIEW

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by lola27** [comment]
hi @Nesma1988 , the side menu stay collapsed when login at first. but I found another issue. After you click the button on the top left to open the side menu, it required another click to close the side menu. this should not happen in mobile view. the side menu should like over the dashboard. when you click any button on the side menu or click outside the side menu, the side menu should auto collapsed as well. just like the notification side nav.

**Comment by kmoore134** [comment]
Jenkins: retest this please

**Comment by kmoore134** [comment]
@lola27 Can you review again?

**Comment by lola27** [comment]
hi @Nesma1988 , it looks pretty nice! thanks. only one small issue. when clicking the button to open the side menu, it seems the menu nav is scrolled down as default. could you fix this one?

**Pull request merged**
