### PR TITLE
NAS-108693 / 21.02 / Have ability to search chart releases in UI and have bulk options / Nas 108693

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Comment by denysbutenko** [comment]
retest this please

**Comment by denysbutenko** [comment]
there is also some conflicts

**Comment by AlexKarpov98** [comment]
Fixed

**Comment by denysbutenko** [comment]
It looks a bit inconsistent with other pages, isn't?
Apps:
localhost_8082_ui_credentials_groups (4)
localhost_8082_ui_credentials_groups (5)
localhost_8082_ui_credentials_groups (2)
localhost_8082_ui_credentials_groups
localhost_8082_ui_credentials_groups (3)

**Comment by denysbutenko** [comment]
`Bulk Options` available even no apps are installed

**Comment by william-gr** [comment]
@AlexKarpov98 probably need to resolve conflicts before we can review again

**Comment by dszidi** [comment]
Here's a PR that should resolve the dynamic toolbar controls issue...

https://github.com/freenas/webui/pull/5086

**Comment by dszidi** [comment]
Almost there. There is an error when clicking the confirm button on the delete dialog

image

**Review by dszidi — APPROVED** [review]
LGTM

**Pull request merged**
