### PR TITLE
Re-Wrote dataset-delete.component to utilize =entity-form instaed of …

### PR DESCRIPTION
**Pull request by psouthwell**
…entity-delete so I cold customize the submit and ask more ten one are you sure question as per ticket feature

### CODE REVIEW

**Comment by psouthwell** [comment]
One little thing to fix first!

**Comment by psouthwell** [comment]
Ok... This is ready to inspect and test now.

**Comment by erinix** [comment]
You should change "Im" to "I'm", you can use ' if you change the quotes from ' to "

**Comment by erinix** [comment]
Or better yet make it "I am"

**Comment by psouthwell** [comment]
hahah... Yap I know about the "'" thing.. I just suck at spelling ;)

**Comment by psouthwell** [comment]
{
      type: 'checkbox',
      name: 'imaware',
      placeholder: T('I am aware that snapsots within this data set will be deleted.'),
      tooltip: T('I am aware that snapsots within this data set will be deleted.   This meas they will not be restorable.'),
      required: true
    }

**Comment by psouthwell** [comment]
Ok to push?

**Comment by erinix** [comment]
LGTM

**Pull request merged**
