### PR TITLE
Cloudsync: check if commit fails with error dialog

### PR DESCRIPTION
**Pull request by mactanxin**
ticket: #31396

### CODE REVIEW

**Comment by lola27** [comment]
build

**Comment by lola27** [comment]
rebuild

**Comment by erinix** [comment]
Looks like you have an AOT error that is causing it to not build, error TS2300: Duplicate identifier 'FormGroup'.[39m[22m[0m

**Comment by mactanxin** [comment]
fixed

**Comment by lola27** [comment]
LGTM

**Pull request merged**
