### PR TITLE
NAS-107735 / 20.12 / Nas 107735 - Certificate Dashboard

### PR DESCRIPTION
**Pull request by dkmullen**
Implements a dashboard for Certificates, CAs, etc for SCALE.
The large forms (for adding Certs, CSRs and CAs) have NOT yet been converted to wizards; this will be done in a separate ticket;

image
image
image
image
image

Design link: https://xd.adobe.com/view/59ee791e-5936-47ca-9768-31d25fa598ab-0cbd/

### CODE REVIEW

**Comment by sonicaj** [comment]
@dkmullen would we be having quick actions as discussed in https://docs.google.com/document/d/1W3_J4_7GbD17kVPv1V1IFjLHH1IFnDXlEITv0R_idn8/edit?disco=AAAAHDk0PjA ?

**Comment by dkmullen** [comment]
@sonicaj From the tables and from the view/edit forms, you can sign a CSR from any CA and you can create an ACME from any CSR. Here are a few new screenshots

Screenshot from 2020-11-18 13-40-35

Screenshot from 2020-11-18 13-42-08


Screenshot from 2020-11-18 13-41-51

**Review by sonicaj — COMMENTED** [review]
It looks good to me, just one more question, we would have scrollbar if the number of certs exceed which can be shown in each box ? Also how would the size of each box be managed ?

I mean currently each box has same number of entries, what happens when the entries are not even wrt box sizes ?

**Comment by dkmullen** [comment]
@sonicaj These tables are using are template that Lola built that 1) Keeps the boxes on each row matched and 2) limits the size and offers a 'Show More'. See pics

Screenshot from 2020-11-19 07-35-58

image

**Review by sonicaj — APPROVED** [review]
Thank you for clarifying

**Review by william-gr — APPROVED** [review]

**Comment by erinix** [comment]
Looks good, the only thing I notice is that the tables look a bit sad when there is nothing in them, maybe add some empty space and/or greyed out text for this case
screenshot-20201119-113934

**Review by erinix — APPROVED** [review]

**Review by Mrt134 — APPROVED** [review]
Public text looks fine

**Review by kmoore134 — APPROVED** [review]

**Pull request merged**
