### PR TITLE
Shell page translation

### PR DESCRIPTION
**Pull request by mactanxin**
ticket: #30348

### CODE REVIEW

**Comment by erinix** [comment]
I am seeing this when I try to build it with aot

```ERROR in : The pipe 'translate' could not be found ("
  <mat-card-title class="mat-bg-primary m-0">
  	 <div class="card-title-text">
  	 	{{[ERROR ->]"Shell" | translate}}
  	 </div>
  </mat-card-title>
")
: The pipe 'translate' could not be found ("
	<mat-card-content>
		<mat-divider class="mb-1"></mat-divider>
		{{[ERROR ->]"Set font size" | translate}}: <mat-slider min="10" max="20" step="1" value="14"  [(ngModel)]="font_s")
: The pipe 'translate' could not be found ("	<button mat-raised-button (click)="resetDefault()" matTooltip="Reset font size to default value">{{[ERROR ->]"Restore default" | translate}}</button>
		<tooltip class="shellTooltip" [message]=shell_tooltip></to")
```

You need to import the translate module into the shell module

**Comment by mactanxin** [comment]
fixed

**Comment by erinix** [comment]
one more thing, the matTooltips should also be piped to translate

**Comment by erinix** [comment]
also this one ```matTooltip="Reset font size to default value"```, you should be able to do something like ```[maTooltip]={{"Reset font size to default value" | translate}}```

**Comment by mactanxin** [comment]
Ah ok, it's a little tricky to make it work with quotes within quotes instead of using variables

**Comment by erinix** [comment]
LGTM

**Pull request merged**
