### PR TITLE
NAS-108688 / 21.02 / Allow access to pod console from UI / NAS-108688

### PR DESCRIPTION
**Pull request by AlexKarpov98**

### CODE REVIEW

**Comment by dszidi** [comment]
Let's use the same icon in the mat-menu-item that we use for the shell in Core. It's console-line from the mdi set.

image

**Review by sonicaj — COMMENTED** [review]
If I set `/bin/bash` as command for minio container, UI does not show the error and user is just presented with an empty screen. It's confusing and we should show the error we get from middleware as otherwise user would probably think that he's going to be presented with console of a container whereas in reality the command has errored out.

**Comment by AlexKarpov98** [comment]
Fixed

**Review by sonicaj — COMMENTED** [review]
I just tried it and it's nice, however we are not refreshing the shell screen on Reconnect, so that can be confusing and we should do that.
Screenshot 2021-01-12 at 10 23 45 PM

**Comment by AlexKarpov98** [comment]
Good point - fixed

**Review by sonicaj — COMMENTED** [review]
We are not refreshing screen after switching pods/containers, please see attached screenshot. I was testing nextcloud app for this which you can use to reproduce. About the erroring out bit, it's working nicely.
Screenshot 2021-01-14 at 12 48 29 AM

**Comment by AlexKarpov98** [comment]
@sonicaj 
It also should be fixed and now I can't see that issue.
Can you please check once again?
Thank you.

**Review by sonicaj — APPROVED** [review]
Thanks

**Comment by kmoore134** [comment]
retest this please

**Review by kmoore134 — APPROVED** [review]
Ran through it here, looks great :)

**Comment by william-gr** [comment]
@freenas/ui-team This has been sitting for review for 9 days, can someone in the UI team review to get t his merged? Thanks!

**Comment by dszidi** [comment]
There are some conflicts since dynamic forms were merged in.

**Comment by kmoore134** [comment]
Ran through the container build again just now, seems to work well if anybody is wanting to merge this.

**Review by dszidi — APPROVED** [review]
LGTM

**Comment by william-gr** [comment]
@dszidi please let developers merge their own PRs.

**Pull request merged**
