### PR TITLE
Entity group table

### PR DESCRIPTION
**Pull request by psouthwell**
Test.  Just seeing if this builds after upgrading to angular-cli@latest

Please don't actually review this.  Im just seeing if it passes.

### CODE REVIEW

**Comment by psouthwell** [comment]
Ok.. This can be merged.

**Comment by erinix** [comment]
I noticed you commented out the tour, could you fix that and then I will merge it?

**Comment by psouthwell** [comment]
cool Erin.   Its been done :)

**Comment by psouthwell** [comment]
wait.. one more inny tinny binny thing in title

**Comment by psouthwell** [comment]
ok Tis Ready Erin.

**Comment by erinix** [comment]
Upon further inspection I notice that I don't see the pool themselves in the in the normal table (perhaps because it isn't a dataset/zvol?), because of this there are no action buttons that would let me delete it or anything.  We need those action buttons on the tree so that the pool can be managed (and maybe just make the tree the default) before this can be pulled in as it

**Comment by erinix** [comment]
But then I refreshed the page and they appeared, not sure why.

**Comment by psouthwell** [comment]
Ok Erin Id like to push this now.. Think the look and feel is more inline.. Wen't a different route to solve it.. but I think the end result is nice.. and close enough to what your saying that you'll also like.. Ive run it in chrome and firefox.. Looks pretty good.. .To me anyways...   Think it's ready for master.

**Comment by psouthwell** [comment]
Lets push this when your comfortable erin :)

**Comment by erinix** [comment]
LGTM - Angular 5!!

**Pull request merged**
