### PR TITLE
Ticket: 26363

### PR DESCRIPTION
**Pull request by Nesma1988**
Completed: https://bugs.freenas.org/issues/26363
Desc: Add Replication Status Indicator

### CODE REVIEW

**Comment by lola27** [comment]
@Nesma1988 I can not see the replication status indicator. Please show us a screenshot of working replication indicator if you have any. thanks

**Comment by lola27** [comment]
one more suggestion, please give a default port value of '22' and encryption cipher of 'standard'.

**Comment by Nesma1988** [comment]
@lola27 Please review again. I have made the changes. I don't understand why it didn't work. I am constantly checking `repl_status` to be `sending`, and when I receive that I am showing an animating icon in the topbar. I didn't have the exact environ to test this but the login should work fine, let me know your thoughts in this.

**Comment by vaibhav-rbs** [comment]
screen shot 2017-11-20 at 2 30 26 pm

**Comment by Nesma1988** [comment]
@vaibhav-rbs 
Changes are made, now it will work, please review.

**Comment by vaibhav-rbs** [comment]
LGTM

**Pull request merged**
