### PR TITLE
leveraging `EntityJobComponent` to watch `mail.send` job to watch it'…

### PR DESCRIPTION
**Pull request by vaibhav-rbs**
…s response. also loosened validation condition for password.

### CODE REVIEW

**Comment by william-gr** [comment]
@vaibhav-rbs this is still going to use saved mail settings credentials to send the test email. Shouldnt it use the settings entering in the current screen form? Otherwise how one can test email without saving it first?

**Comment by vaibhav-rbs** [comment]
@william-gr oh I did not thought about the scenario where user would be sending a test email without saving the form first, now that you have mentioned now it makes sense, to try sending test email with the current values in the form.

**Comment by erinix** [comment]
Jenkins: retest this please

**Comment by erinix** [comment]
Jenkins: retest this please

**Comment by erinix** [comment]
LGTM

**Pull request merged**
