### PR TITLE
Cloudcreds tooltip review

### PR DESCRIPTION
**Pull request by Mrt134**
Review and reduce existing tooltips. Add missing tooltip. Local testing with npm: no issues.

### CODE REVIEW

**Comment by erinix** [comment]
Please fix your merge conflicts

**Comment by erinix** [comment]
That's weird, it shows the files changed to be 0 with 0 commits and no tootip changes to review

**Comment by Mrt134** [comment]
huh, weird. I'll look into it :)

**Comment by Mrt134** [comment]
Ok, looks like the different files got consolidated into one single file for each Cloud Cred. option, which removed my previous commit. I've redone the commit and tested again with npm: no issues.

**Comment by erinix** [comment]
LGTM

**Pull request merged**
