### PR TITLE
Review Storage tooltips:

### PR DESCRIPTION
**Pull request by Mrt134**
- Review files under the Storage menu and clean up tooltips.
- Also clean up whitespace.

### CODE REVIEW

**Comment by erinix** [comment]
Please fix your merge conflicts

**Comment by erinix** [comment]
sorry this section is just under heavy construction right now :(

**Comment by Mrt134** [comment]
No biggie, I was pretty much expecting to run into this now and again. :)

**Comment by erinix** [comment]
LGTM

**Pull request merged**
