### PR TITLE
Nas 103596

### PR DESCRIPTION
**Pull request by lola27**

### CODE REVIEW

**Comment by lola27** [comment]
@freenas/docs-team Could you please provide the tooltips? thanks

**Comment by erinix** [comment]
code looks ok, just needs tooltips

**Comment by wblock** [comment]
I only see helptext.name_tooltip.  That variable name should be a lot more specific.  Are there any others that need to be filled out?

**Comment by lola27** [comment]
> I only see helptext.name_tooltip. That variable name should be a lot more specific. Are there any others that need to be filled out?

yes. They are more fields in the helptext/ssh-connections.ts need to be filled out, especially for the host and url field.

**Comment by wblock** [comment]
I meant that a variable called just helptext.name_tooltip does not give any idea what it is a name *of*.
As far as other helptext, I don't see from this code what is needed.

**Pull request merged**
