### PR TITLE
Update 16th February 2020

### PR DESCRIPTION
**Pull request by Liliththerebel**
I hope everything is right, 
in case of any doubt do not hesitate to contact me.
Regards

### CODE REVIEW

**Comment by erinix** [comment]
looks like you have some conflicts, I would recommend doing a git pull before you start translating

**Comment by Liliththerebel** [comment]
Hi Erin
Nevertheless I am very willing and motivated to translate Freenas, I am also a newbie to github. Could you please help me to improve my translation process? How do I make a git pull before translating?
Thanks!

Regards!

Lilith

**Comment by erinix** [comment]
Are you using the command prompt or some kind of utility to manage git?

**Comment by Liliththerebel** [comment]
No I usually edit from website editor. Is there something wrong?

**Comment by erinix** [comment]
I mean the main problem we are facing is that there is a conflict which means your master is probably out of date.  I would suggest two things, don't work directly off of master on your github page and create a new branch when you make some new translations, this way you can keep master up to date without your commits getting in the way.  You might try some kind of GUI github management utility to work with too if that helps you, I do not know which one to recommend as I just use the "git" command but I'm sure one of these might make your life easier https://www.tecmint.com/best-gui-git-clients-git-repository-viewers-for-linux/

**Comment by erinix** [comment]
I created another PR with your commit and the merge conflicts fixed in it, see https://github.com/freenas/webui/pull/3664.  I will go ahead and close this one for now, thanks for your continued efforts :)

**Pull request closed without merging**
