### PR TITLE
Daisuke webui fix #26413

### PR DESCRIPTION
**Pull request by dasukeImaimobile**
I completed https://bugs.freenas.org/issues/26413

### CODE REVIEW

**Comment by lola27** [comment]
The basic mode looks nice! Thanks @dasukeImaimobile ! But the advanced mode is not finished. Could you finish that as well? then I can review it again. Thanks.

**Comment by vaibhav-rbs** [comment]
@dasukeImaimobile  can you please respond to @lola27 review ?

**Comment by dasukeImaimobile** [comment]
Hi Lola,
I will double-check soon. I saw these messages a few minutes ago. I am sorry.

**Comment by lola27** [comment]
no worries :)

**Comment by dasukeImaimobile** [comment]
@lola27 I updated the advanced mode. Please review and let me know if I did exactly.
Thanks.

**Comment by lola27** [comment]
Thanks Daisuke! 
1. basic mode form looks good, but no matter what you select for time, date, repeat fields, the following properties will be the same.
```{  
   "cron_daymonth":"*",
   "cron_dayweek":"*",
   "cron_hour":"*",
   "cron_minute":"00",
   "cron_month":"*",
}
```
2. advance mode, for these fileds - minute, hour, day of month, month, and day of week, it should allows users to do multi-select. 
3. edit cron job not finished.

**Pull request closed without merging**
