### PR TITLE
i18n: es-ar.po updated

### PR DESCRIPTION
**Pull request by castillofrancodamian**
Signed-off-by: Franco Castillo <castillofrancodamian@gmail.com>

### CODE REVIEW

**Comment by castillofrancodamian** [comment]
It's okay!

**Comment by castillofrancodamian** [comment]
What would it be called es-ar?

**Comment by erinix** [comment]
yea es-ar :) I went ahead and merged this one but feel free to add that entry on your next PR

**Comment by castillofrancodamian** [comment]
I was wondering how you should call es-ar.po in the README.md file.

**Pull request merged**
