### PR TITLE
Added the tooltips for the Import CA page.

### PR DESCRIPTION
**Pull request by sambonham**

### CODE REVIEW

**Comment by lola27** [comment]
LGTM

**Comment by erinix** [comment]
Jenkins: retest this please

**Comment by erinix** [comment]
Jenkins: retest this please

**Comment by erinix** [comment]
I think you might need redo this one, (you could probably just snag the diff and resubmit it), it wouldn't let me pull and I think it had more to do with your local repo not being there anymore

**Comment by Mrt134** [comment]
This one can be closed - we've since added these tooltips.

**Comment by Mrt134** [comment]
I checked with sambonham and confirmed it's ok to close this one.

**Pull request closed without merging**
