### PR TITLE
Update fr.po

### PR DESCRIPTION
**Pull request by MDVAurelien**
Update of some translations

### CODE REVIEW

**Comment by erinix** [comment]
if you want your changes in 11.3 please also make a PR that targets freenas/11.3-stable

**Comment by MDVAurelien** [comment]
Thank you it's done. In your opinion how I can visualize the modifications on the 11.3 branch? Is it always with nightly builds? I now have to do my translations on the two branches (11.3 and Master)? Thks & Happy new year ;-)

**Comment by erinix** [comment]
at this point the nightlies will be 12, the only way to really see 11.3 will be in releases or alternatively you could try setting up the build environment as per the README file

**Comment by MDVAurelien** [comment]
Thank you Erin, that's clear.

**Pull request merged**
