### PR TITLE
Adjust tooltip icon size and placement (Chentao fix #26723)

### PR DESCRIPTION
**Pull request by Allwithyou999**
https://redmine.ixsystems.com/issues/26723

Adjusted tooltip icon size and placement, added an animation, fixed mobile responsive of Tooltip alert.

### CODE REVIEW

**Comment by vaibhav-rbs** [comment]
LGTM

**Comment by vaibhav-rbs** [comment]
looks like we have a merge conflict @Allwithyou999 please resolve.

**Comment by Allwithyou999** [comment]
@vaibhav-rbs  Merge conflict was fixed. Please review. Thanks

**Comment by vaibhav-rbs** [comment]
LGTM

**Pull request merged**
