### PR TITLE
NAS-108586 / 21.02 / Fix pool actions when status is OFFLINE

### PR DESCRIPTION
**Pull request by dszidi**
Fix pool actions when status is OFFLINE

### CODE REVIEW

**Review by kmoore134 — APPROVED** [review]
Reviewed the visual side of it last night, LGTM.

**Comment by william-gr** [comment]
Lets use a sane description for the PRs, please

**Review by ryousaf — APPROVED** [review]
LGTM

**Review by denysbutenko — APPROVED** [review]
LGTM

**Review by william-gr — APPROVED** [review]

**Pull request merged**
